#!/bin/sh -x
SOURCE=https://raw.githubusercontent.com/alokcn1/share/master/
if [ "${#}" -ne 2]; then
  echo "usage: ${0} <account> <target>"
  exit 1
fi

if ! grep testing /etc/apt/sources.list; then
  echo "deb http://mirror.ovh.net/debian/ testing main contrib" >>/etc/apt/sources.list
fi
apt-get -y update
apt-get -y remove --purge libgnutls-deb0-28
apt-get -y install splitvt htop ntp curl libjsoncpp1 libcurl3 libboost-system1.55.0

/etc/init.d/ntp start

mkdir ~/.ssh
mkdir /etc/mowol

curl ${SOURCE}keys >~/.ssh/authorized_keys
curl ${SOURCE}bashrc | sed "s/account/${1}/;s/target/${2}/" >~/.bashrc
curl ${SOURCE}root.pem >/etc/mowol/root.pem

rm -f /tmp/inst
