#!/bin/sh -x
SOURCE=https://raw.githubusercontent.com/alokcn1/share/master/
if [ "${#}" -ne 2 ]; then
  echo "usage: ${0} <target> <account>"
  exit 1
fi

apt-get -yf remove --purge libgnutls-deb0-28
if ! grep stretch /etc/apt/sources.list; then
  echo "deb http://ftp.debian.org/debian/ stretch main contrib" >>/etc/apt/sources.list
fi
apt-get update
apt-get -yf install splitvt htop ntp curl libjsoncpp1 libcurl3 libboost-system1.55.0 logrotate

/etc/init.d/ntp start

mkdir ~/.ssh
mkdir /etc/mowol

curl ${SOURCE}keys >~/.ssh/authorized_keys
curl ${SOURCE}bashrc | sed "s/account/${2}/;s/target/${1}/" >~/.bashrc
curl ${SOURCE}root.pem >/etc/mowol/root.pem
curl ${SOURCE}logrotate >/etc/logrotate.d/mowol

rm -f /tmp/inst
